services:
  react:
    build: .
    volumes:
      - react-build:/app/build
    environment:
      - REACT_APP_API_BASE_URL = "http://localhost:8000"

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - react-build:/usr/share/nginx/html:ro
    depends_on:
      - react

volumes:
  react-build: